### ISSUE TITLE
Purchase Raspberry Pi

### ISSUE THREAD

**Issue by james-herbstritt** [flicr-capstone/issues#1]
Buy the Raspberry Pi for FLiCR.

**Comment by mmgoodnow** [comment]
https://www.amazon.com/CanaKit-Raspberry-Basic-Kit-4GB/dp/B07TXKY4Z9.

$75, 40 more than we were expecting. However seeing as we will be doing three video transcoding streams I think we can take as much power as we can get.

**Comment by mmgoodnow** [comment]
Buying.

**Comment by james-herbstritt** [comment]
We now have the Raspberry Pi
