### ISSUE TITLE
Write a document on how to set up the dev environment

### ISSUE THREAD

**Issue by mmgoodnow** [flicr-capstone/issues#17]
With potentially 4 of us touching the code this is something that will be helpful to get developers up and running quickly, and to make sure that nobody commits dirty code.

**Comment by mmgoodnow** [comment]
It is up at https://github.com/flicr-capstone/issues/wiki/Software-Manual.

@bochola Since you'll be the first one going through this document let me know how clear it is and if there's anything else I should add.

cc @james-herbstritt

**Comment by james-herbstritt** [comment]
Looks good!

**Comment by james-herbstritt** [comment]
Looks good!
