### ISSUE TITLE
Decide on Protocol for data transfer

### ISSUE THREAD

**Issue by james-herbstritt** [flicr-capstone/issues#21]

**Comment by mmgoodnow** [comment]
The way I've got it set up currently is that messages going both directions will look approximately like the following:

```js
{
    "type": string,
    "msg": any
}
```

On the back end I set up a triage function, sort of inspired by Redux (with `switch (actionType)`). It'll just be a long elif chain (bc no switch in python) checking the type enum and then calling whatever function. 

On the front end it'll be a little different bc we're using RxJS, so it'll probably be more like filtering the observable stream down to the ones only with the type you're interested in, then subscribing to that.
