### ISSUE TITLE
Set up FE deployment

### ISSUE THREAD

**Issue by mmgoodnow** [flicr-capstone/issues#5]

**Comment by mmgoodnow** [comment]
Test

**Comment by mmgoodnow** [comment]
test

**Comment by mmgoodnow** [comment]
Should be auto deploying now. 

https://flicr.bebopbeluga.com

**Comment by mmgoodnow** [comment]
Added slack posts so we can see when the build fails.

**Comment by james-herbstritt** [comment]
Does auto-deploy and have received slack notifications.
