### ISSUE TITLE
Implement client side view for streaming pipeline using janus API

### ISSUE THREAD

**Issue by james-herbstritt** [flicr-capstone/issues#58]
Janus has a JavaScript API which we will use to make our client side streaming window.

**Comment by mmgoodnow** [comment]
https://janus.conf.meetecho.com/docs/JS.html

**Comment by mmgoodnow** [comment]
We have made some good progress on this today. We used the Janus JS api to interface with the server and initiate a stream, but got stuck on displaying the stream.
