### ISSUE TITLE
Finalize the battery choice for lil buddy

### ISSUE THREAD

**Issue by bochola** [flicr-capstone/issues#59]
Search for a suitable power source that can power the DC motors, drive motors, and the Raspberry Pi.

We found [these batteries](https://www.amazon.com/GOLDBAT-5200mAh-Battery-Traxxas-Associated/dp/B07Z4P33BR/ref=sr_1_6?keywords=5200mah+lipo+battery&qid=1579240484&sr=8-6), similar to the Sawppy robot.

We need to determine whether or not 2 or 3 of these batteries will be able to provide enough amp-hours to power the entire robot for at least 2 hours before recharging.

We should also look into how to recharge these batteries and how specifically we would connect to the pins. They seem to use deans connections for the power discharge

**Comment by james-herbstritt** [comment]
@bochola @jtukpah Can this be closed?
